name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish -o ./publish-out
    
    - name: SSH Deploy
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOY_SERVER }}
        username: Administrator
        password: ${{ secrets.DEPLOY_PASSWORD }}
        port: 22
        source: "./publish-out"
        target: "C:\\Websites\\HexDemo"
